steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_STATS_API_URL=${_NEXT_PUBLIC_STATS_API_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_CTI_BACKEND_URL=${_NEXT_PUBLIC_CTI_BACKEND_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_STATS_API_URL=${_NEXT_PUBLIC_STATS_API_URL}'

substitutions:
  _SERVICE_NAME: symbiotic-thinking-dojo
  _REGION: us-central1
  _NEXT_PUBLIC_STATS_API_URL: 'https://dojo-stats-api.netlify.app'
  _NEXT_PUBLIC_CTI_BACKEND_URL: 'https://dojo-backend-dgn5kavnea-uc.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
