"""insert initial admin key

Revision ID: c368df9d72a8
Revises: 5d9227c787ea
Create Date: 2026-06-19 12:49:19.482726

"""
from typing import Sequence, Union
import os
import secrets

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c368df9d72a8'
down_revision: Union[str, None] = '5d9227c787ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if admin key is provided via environment variable
    admin_key = os.environ.get('INITIAL_ADMIN_KEY')

    if not admin_key:
        # Generate a secure random key if not provided
        admin_key = secrets.token_hex(32)
        print(f"\n{'='*60}")
        print(f"GENERATED ADMIN KEY: {admin_key}")
        print(f"{'='*60}\n")
        print("Save this key securely - it will not be shown again!")

    # Insert the admin key using connection for proper parameter binding
    from sqlalchemy import text
    connection = op.get_bind()
    connection.execute(text("""
        INSERT INTO admin_keys (id, key_value, label, active, created_at, notes)
        VALUES (
            gen_random_uuid()::text,
            :admin_key,
            'Initial Admin Key',
            TRUE,
            NOW(),
            'Auto-generated by migration'
        );
    """), {'admin_key': admin_key})


def downgrade() -> None:
    op.execute("""
        DELETE FROM admin_keys WHERE label = 'Initial Admin Key';
    """)
